import localFont from 'next/font/local';
import "./globals.css";
import '../styles/common.scss';

import SmoothScrolling from './components/SmoothScrolling';

const pretendard = localFont({
  src: "../public/fonts/pretendard/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body className={pretendard.className}>
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
